### PR TITLE
OPENCAST-855: Exposed download options for LR episodes

### PR DESCRIPTION
**Pull request by npmali**

### CODE REVIEW

**Comment by npmali** [comment]
Link to test: 

https://media.uct.ac.za/ltitools/courses2/index.html?sid=c8c41822-531d-4256-b773-033d354a2aa9&upload=false

**Comment by smarquard** [comment]
The download descriptions should be the same as we have in the Download tab in the player.

The animations are a bit slow and should be snappier.

Also please check how this behaves on mobile devices (small viewports) - test full-screen, tablet-size and mobile.

**Comment by smarquard** [comment]
Bonus points if you can make the download also trigger a POST to the usertracking endpoint to record a play event the same way that Theodul player does. But we shouldn't post more than one play event for different download for the same event (so if you download 3 different formats, still only 1 event).

Otherwise we lose some playback stats from these downloads.

**Comment by npmali** [comment]
> Bonus points if you can make the download also trigger a POST to the usertracking endpoint to record a play event the same way that Theodul player does. But we shouldn't post more than one play event for different download for the same event (so if you download 3 different formats, still only 1 event).
> 
> Otherwise we lose some playback stats from these downloads.

Working on it

**Comment by smarquard** [comment]
bootstrap and underscore seem to be duplicated (in both shared and courses).

**Comment by npmali** [comment]
Duplicate files removed from courses

**Review by TurRil — APPROVED** [review]

**Pull request merged**
